version: "3.8"

services:
  discovery-service:
    build:
      context: ./discovery-service  # Use the Dockerfile in the discovery-service directory
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - kala-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      retries: 3

  config-server:
    build:
      context: ./config-server  # Use the Dockerfile in the config-server directory
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
    networks:
      - kala-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/KALA2501/Archivos-config.git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=main
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      retries: 3

  api-gateway:
    build:
      context: ./api-gateway  # Use the Dockerfile in the api-gateway directory
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - discovery-service
    networks:
      - kala-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      retries: 3

  usuarios-service:
    build:
      context: ./usuarios-service  # Use the Dockerfile in the usuarios-service directory
    container_name: usuarios-service
    ports:
      - "9091:9091"
    depends_on:
      - config-server
      - discovery-service
    networks:
      - kala-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/actuator/health"]
      interval: 30s
      retries: 3

  frontend:
    build:
      context: ./frontend  # Use the Dockerfile in the frontend directory
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
      - discovery-service
      - config-server
    networks:
      - kala-network
    restart: always
    environment:
      - REACT_APP_API_URL=http://api-gateway:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      retries: 3

networks:
  kala-network:
    driver: bridge
